name: flutter_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  uuid: ^3.0.7
  flutter_slidable: ^3.0.0
  
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  meta: ^1.9.1
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
